spring.application.name=galaxy
spring.security.user.name=user
spring.security.user.password=pass

# データベース設定
spring.datasource.url=jdbc:h2:file:./data/galaxydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# NASA API Key設定
nasa.api.key=XBO0HtcoMH8zzTcCrFdObI3bA1RWtWmY5dGhBEPK